name: Amazon Linux Python Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python 3.8 using amazon-linux-extras
      run: |
        sudo amazon-linux-extras install -y python3.8

    - name: Verify Python Installation
      run: python3.8 --version

    - name: Run Python script
      run: python3.8 app.py
