name: Custom Python Installation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and Install Python
      run: |
        # Download the Python package
        wget https://github.com/actions/python-versions/releases/download/3.12.0-rc.1-5785015073/python-3.12.0-rc.1-darwin-x64.tar.gz

        # Extract the contents of the package
        tar -xzf python-3.12.0-rc.1-darwin-x64.tar.gz

        # Move the extracted Python directory to a desired location
        sudo mv python-3.12.0-rc.1-darwin-x64 /usr/local/custom-python

        # Add the custom Python installation to the PATH
        export PATH="/usr/local/custom-python/bin:$PATH"

    - name: Verify Python Installation
      run: python3.12 --version

    - name: Run Python script
      run: python3.12 app.py
